version: '3.8'

services:
  app:
    build: .
    container_name: stylemind_api
    restart: always
    env_file:
      - stack.env
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db_stylemind:5432/stylemind?schema=public
      REDIS_HOST: redis_stylemind

    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
        restart: true
      redis:
        condition: service_started


    command: yarn run start:migrate:prod

  db:
    container_name: 'db_stylemind'
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: stylemind
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward PostgreSQL locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  redis: 
    container_name: redis_stylemind
    image: redis:bookworm
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  postgres-data:
  redis-data:
